openapi: "3.0.1"
info:
  version: "1"
  title: "Epiblog documentation"


servers:
  - url: "https://{api_id}.execute-api.eu-west-3.amazonaws.com/live"
    variables:
      api_id:
        default: api_id
        description: set api id

paths:
  /articles:
    post:
      summary: "Create an article"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        201:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
      security:
        - sigv4: [ ]
      x-amazon-apigateway-request-validator: validate_request
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 201
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateArticleFunction.Arn}/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

    get:
      summary: "Find article by tag"
      parameters:
        - in: query
          name: tag
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Article"
      security:
        - sigv4: [ ]
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FindArticlesFunction.Arn}/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
        
  /articles/{article_id}:
    get:
      summary: "Find article by article_id"
      parameters:
        - in: path
          name: article_id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
      security:
        - sigv4: [ ]
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FindArticleFunction.Arn}/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
    delete:
      summary: "Delete an article"
      parameters:
        - in: path
          name: article_id
          required: true
          schema:
            type: string
      responses:
        204:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: [ ]
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 204
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteArticleFunction.Arn}/invocations"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: string
        author:
          type: string
        title:
          type: string
        genre:
          type: string
        date:
          type: string
    Empty:
      type: object

securityDefinitions:
  sigv4:
    type: apiKey
    name: Authorization
    in: header
    x-amazon-apigateway-authtype: awsSigv4

  authorizer:
    type: apiKey
    name: Authorization
    in: header
    x-amazon-apigateway-authtype: 'custom'
    x-amazon-apigateway-authorizer:
      type: token
      authorizerUri: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AuthorizerFunction}/invocations


x-amazon-apigateway-request-validators:
  validate_request:
    validateRequestBody: true
    validateRequestParameters: true
