name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup python
      run: |
        apt-get update
        apt-get install -y python3-pip
        python3 -m pip install --upgrade pip
      
    - name: Install invoke
      run: python3 -m pip install invoke wget configobj psutil

    - name: Invoke bootstrap
      run: invoke bootstrap

    - name: Deploy the CloudFormation stack
      run: invoke stack-deploy -c epiblog-back
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
